language: node_js
node_js: 
  - 13

services:
  - docker 

# Pre-testing installs 
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests 
before_script:
  - echo "no tests"

script: 
  - docker --version # print the docker version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed jisegun1/udagram-api-feed

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user jisegun1/udagram-api-user

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend jisegun1/udagram-frontend:local

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy jisegun1/reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jisegun1/udagram-api-feed
  - docker push jisegun1/udagram-api-user
  - docker push jisegun1/udagram-frontend:local
  - docker push jisegun1/reverseproxy